name: PublicKits
main: com.github.caaarlowsz.publicmc.kitpvp.Main
version: 1.0
author: Kiwwi_
commands:
  fps:
  quest2:
  invsee:
  inf:
  effect:
  diario:
  cc:
  level:
  dragon:
  setdragon:
  ffeast:
  setffeast:
  rfeast:
  urano:
  sethard:
  hard:
  resetkit:
  click:
  cash:
  setlava:
  quest1:
  quests:
  build:
  sopinha:
  pegasus:
  lava:
  potion:
  spawn:
  setspawn:
  setpotion:
  setrdm:
  rdm:
  mdr:
  setmdr:
  knock:
  gm:
  bc:
  report:
  feast:
  setfeast:
  setfps: 
  setknock:
  pvp:  
  loja:
  abrirrdm:
  fecharrdm:
  admin:
  kangaroo:
  principal:
  setprincipal:
  firer:
  kreload:
  supernova:
  mago:
  tornado:
  evolucionist:
  gon:
  recraft:
  zeus:
  ninja:
  sonic:
  deshfire:
  stomper:
  woodman:
  viking:
  surprise:
  velotrol:
  thor:
  tag:
  terrorista:
  turtle:
  boxer:
  viper:
  fisherman:
  endermage:
  kits: