package zEvents;

import java.util.ArrayList;

import org.bukkit.Bukkit;
import org.bukkit.Color;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.LeatherArmorMeta;
import org.bukkit.potion.PotionEffectType;

import zKits.Arrays;
import zKits.DeshFire;
import zKits.Firer;
import zKits.Flyer;
import zKits.KitsManager;
import zKits.Ninja;
import zKits.Sonic;
import zKits.Supernova;
import zKits.Terrorista;
import zKits.Tornado;
import zKits.Wither;
import com.github.caaarlowsz.publicmc.kitpvp.PublicPvP;

public class Inf implements CommandExecutor, Listener {
	public static ArrayList<Player> dly;

	static {
		Inf.dly = new ArrayList<Player>();
	}

	public boolean onCommand(final CommandSender sender, final Command cmd, final String tag, final String[] args) {
		if (!(sender instanceof Player)) {
			sender.sendMessage("�cVoc\u00ea n\u00e3o \u00e9 um jogador");
			return true;
		}
		final Player p = (Player) sender;
		if (tag.equalsIgnoreCase("inf")) {
			if (!p.hasPermission("kitpvp.inf")) {
				p.sendMessage("�cSem Permiss\u00e3o!");
				return true;
			}
			p.sendMessage("�7[�6>�7]�7Para setar warps use /set e a warp desejada");
			p.sendMessage(" ");
			p.sendMessage("�7[�6>�7]�7Para abir a rdm use /rdmabir ou para fechar /rdmfechar");
			p.sendMessage(" ");
			p.sendMessage("�7[�6>�7]�7Para spawnar Villagers de Sopa Use /sopinha e /recraft");
			p.sendMessage(" ");
			p.sendMessage("�7[�6>�7]�7Para dar level para players use /cash add nick quantidade");
			p.sendMessage(" ");
			p.sendMessage(
					"�7[�6>�7]�7Voc\u00ea Pode spawnar um feast quando quiser usando /ffeast e remove-lo usando  /rfeast");
			p.sendMessage(" ");
			p.sendMessage("�7[�6>�7]�7Para setar a posi\u00e7\u00e3o deste feast use /setffeast");
			return true;
		} else {
			if (cmd.getName().equalsIgnoreCase("cc") && p.hasPermission("kitpvp.inf")) {
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" ");
				p.sendMessage(" �7�o Chat Limpo.");
			}
			if (cmd.getName().equalsIgnoreCase("resetkit") && p.hasPermission("kitpvp.resetkits")) {
				Arrays.removeAbility(p);
				Sonic.cooldownm.remove(p);
				Terrorista.cooldownm.remove(p);
				DeshFire.cooldownm.remove(p);
				Ninja.cooldownbk.remove(p);
				Firer.cooldownm.remove(p);
				Supernova.cooldownm.remove(p);
				Tornado.cooldownm.remove(p);
				Flyer.cooldownm.remove(p);
				Wither.cooldown.remove(p.getName());
				Sonic.cooldownm.remove(p);
				Arrays.used.remove(p.getName());
				Arrays.pvp.remove(p.getName());
				Arrays.magma.remove(p.getName());
				Arrays.desh.remove(p.getName());
				Arrays.ninja.remove(p.getName());
				Arrays.troll.remove(p.getName());
				Arrays.shadow.remove(p.getName());
				Arrays.gelo.remove(p.getName());
				Arrays.avatar.remove(p.getName());
				Arrays.stomper.remove(p.getName());
				Arrays.viper.remove(p.getName());
				Arrays.urgal.remove(p.getName());
				Arrays.turtle.remove(p.getName());
				Arrays.terrorista.remove(p.getName());
				Arrays.endermage.remove(p.getName());
				Arrays.pulo.remove(p.getName());
				Arrays.ironman.remove(p.getName());
				Arrays.kriptonita.remove(p.getName());
				Arrays.reaper.remove(p.getName());
				p.getInventory().clear();
				final ItemStack item12 = new ItemStack(Material.DIAMOND);
				final ItemMeta itemmeta12 = item12.getItemMeta();
				itemmeta12.setDisplayName("�a Warps");
				item12.setItemMeta(itemmeta12);
				p.getInventory().setItem(2, item12);
				final ItemStack item13 = new ItemStack(Material.CHEST);
				final ItemMeta itemmeta13 = item13.getItemMeta();
				itemmeta13.setDisplayName("�a Seletor de Kits");
				item13.setItemMeta(itemmeta13);
				p.getInventory().setItem(4, item13);
				final ItemStack item14 = new ItemStack(Material.IRON_INGOT);
				final ItemMeta itemmeta14 = item14.getItemMeta();
				itemmeta14.setDisplayName("�a Extras");
				item14.setItemMeta(itemmeta14);
				p.getInventory().setItem(6, item14);
				p.sendMessage(" �bKit removido.");
			}
			if (!cmd.getName().equalsIgnoreCase("dragon")) {
				return false;
			}
			if (PublicPvP.cash.get(p) >= 20) {
				if (PublicPvP.getPlugin().getConfig().getConfigurationSection("dragon") == null) {
					p.sendMessage("�cDragon Nao Setado!");
					return true;
				}
				final World w = Bukkit.getServer().getWorld(PublicPvP.getPlugin().getConfig().getString("dragon.world"));
				final double x = PublicPvP.getPlugin().getConfig().getDouble("dragon.x");
				final double y = PublicPvP.getPlugin().getConfig().getDouble("dragon.y");
				final double z = PublicPvP.getPlugin().getConfig().getDouble("dragon.z");
				p.teleport(new Location(w, x, y, z));
				p.getInventory().clear();
				final ItemStack Peitoral = new ItemStack(Material.LEATHER_CHESTPLATE);
				final LeatherArmorMeta kPeitoral = (LeatherArmorMeta) Peitoral.getItemMeta();
				kPeitoral.setColor(Color.fromRGB(140, 23, 23));
				Peitoral.setItemMeta((ItemMeta) kPeitoral);
				p.getInventory().setChestplate(Peitoral);
				final ItemStack Capacete = new ItemStack(Material.LEATHER_HELMET);
				final LeatherArmorMeta kCapacete = (LeatherArmorMeta) Capacete.getItemMeta();
				kCapacete.setColor(Color.fromRGB(140, 23, 23));
				Capacete.setItemMeta((ItemMeta) kCapacete);
				final ItemStack Calca = new ItemStack(Material.LEATHER_LEGGINGS);
				final LeatherArmorMeta kCalca = (LeatherArmorMeta) Calca.getItemMeta();
				kCalca.setColor(Color.fromRGB(140, 23, 23));
				Calca.setItemMeta((ItemMeta) kCalca);
				final ItemStack Bota = new ItemStack(Material.LEATHER_BOOTS);
				final LeatherArmorMeta kBota = (LeatherArmorMeta) Bota.getItemMeta();
				kBota.setColor(Color.fromRGB(140, 23, 23));
				Bota.setItemMeta((ItemMeta) kBota);
				p.getInventory().setHelmet(Capacete);
				p.getInventory().setLeggings(Calca);
				p.getInventory().setBoots(Bota);
				final ItemStack item15 = new ItemStack(Material.FIREBALL);
				final ItemMeta itemmeta15 = item15.getItemMeta();
				itemmeta15.setDisplayName("�c Drag\u00e3o");
				item15.setItemMeta(itemmeta15);
				p.setAllowFlight(true);
				p.getInventory().setItem(1, item15);
				final ItemStack item16 = new ItemStack(Material.STONE_SWORD);
				final ItemMeta itemmeta16 = item16.getItemMeta();
				itemmeta16.setDisplayName("�c SwordDragon");
				item16.setItemMeta(itemmeta16);
				p.setAllowFlight(true);
				p.getInventory().setItem(0, item16);
				KitsManager.darSopas(p);
				p.removePotionEffect(PotionEffectType.INCREASE_DAMAGE);
				p.removePotionEffect(PotionEffectType.SPEED);
			}
			if (cmd.getName().equalsIgnoreCase("dragon")) {
				if (PublicPvP.cash.get(p) >= 20) {
					if (PublicPvP.getPlugin().getConfig().getConfigurationSection("dragon") == null) {
						p.sendMessage("�cDragon Nao Setado!");
						return true;
					}
					final World w = Bukkit.getServer().getWorld(PublicPvP.getPlugin().getConfig().getString("dragon.world"));
					final double x = PublicPvP.getPlugin().getConfig().getDouble("dragon.x");
					final double y = PublicPvP.getPlugin().getConfig().getDouble("dragon.y");
					final double z = PublicPvP.getPlugin().getConfig().getDouble("dragon.z");
					p.teleport(new Location(w, x, y, z));
					p.getInventory().clear();
					final ItemStack Peitoral = new ItemStack(Material.LEATHER_CHESTPLATE);
					final LeatherArmorMeta kPeitoral = (LeatherArmorMeta) Peitoral.getItemMeta();
					kPeitoral.setColor(Color.fromRGB(140, 23, 23));
					Peitoral.setItemMeta((ItemMeta) kPeitoral);
					p.getInventory().setChestplate(Peitoral);
					final ItemStack Capacete = new ItemStack(Material.LEATHER_HELMET);
					final LeatherArmorMeta kCapacete = (LeatherArmorMeta) Capacete.getItemMeta();
					kCapacete.setColor(Color.fromRGB(140, 23, 23));
					Capacete.setItemMeta((ItemMeta) kCapacete);
					final ItemStack Calca = new ItemStack(Material.LEATHER_LEGGINGS);
					final LeatherArmorMeta kCalca = (LeatherArmorMeta) Calca.getItemMeta();
					kCalca.setColor(Color.fromRGB(140, 23, 23));
					Calca.setItemMeta((ItemMeta) kCalca);
					final ItemStack Bota = new ItemStack(Material.LEATHER_BOOTS);
					final LeatherArmorMeta kBota = (LeatherArmorMeta) Bota.getItemMeta();
					kBota.setColor(Color.fromRGB(140, 23, 23));
					Bota.setItemMeta((ItemMeta) kBota);
					p.getInventory().setHelmet(Capacete);
					p.getInventory().setLeggings(Calca);
					p.getInventory().setBoots(Bota);
					final ItemStack item15 = new ItemStack(Material.FIREBALL);
					final ItemMeta itemmeta15 = item15.getItemMeta();
					itemmeta15.setDisplayName("�c Drag\u00e3o");
					item15.setItemMeta(itemmeta15);
					p.setAllowFlight(true);
					p.getInventory().setItem(1, item15);
					final ItemStack item16 = new ItemStack(Material.STONE_SWORD);
					final ItemMeta itemmeta16 = item16.getItemMeta();
					itemmeta16.setDisplayName("�c SwordDragon");
					item16.setItemMeta(itemmeta16);
					p.setAllowFlight(true);
					p.getInventory().setItem(0, item16);
					KitsManager.darSopas(p);
					p.removePotionEffect(PotionEffectType.INCREASE_DAMAGE);
					p.removePotionEffect(PotionEffectType.SPEED);
				}
				return false;
			}
			return false;
		}
	}
}
